### ISSUE TITLE
Error when SSH to the GNS3 VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#84]
```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-27-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Fri Sep  2 06:09:10 2016
Traceback (most recent call last):
  File "/usr/local/bin/gns3welcome.py", line 28, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
If the GNS3 menu is no longer working run sudo gns3restore
gns3@gns3vm:~$
```

**Comment by AJNOURI** [comment]
From the community forum:

https://gns3.com/qa/recurring-memoryerror-when-using

---------------
Looks like the issue resurfaced again:
